import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790685125417 implements MigrationInterface {
    name = 'InitialSchema1790685125417'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" text, "avatar" character varying, "maxMembers" integer NOT NULL DEFAULT '5', "isPublic" boolean NOT NULL DEFAULT false, "faculty" character varying, "department" character varying, "metadata" jsonb DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."team_members_role_enum" AS ENUM('leader', 'member')`);
        await queryRunner.query(`CREATE TABLE "team_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teamId" uuid, "userId" uuid, "role" "public"."team_members_role_enum" NOT NULL DEFAULT 'member', "isActive" boolean NOT NULL DEFAULT true, "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca3eae89dcf20c9fd95bf7460aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'success', 'warning', 'error', 'deadline', 'mention', 'evaluation', 'team', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "title" character varying(200) NOT NULL, "message" text NOT NULL, "actionUrl" character varying, "entityType" character varying, "entityId" character varying, "isRead" boolean NOT NULL DEFAULT false, "isEmailSent" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_rooms_type_enum" AS ENUM('project', 'team', 'direct', 'general')`);
        await queryRunner.query(`CREATE TABLE "chat_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "type" "public"."chat_rooms_type_enum" NOT NULL DEFAULT 'project', "entityId" character varying, "memberIds" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c69082bd83bffeb71b0f455bd59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_type_enum" AS ENUM('text', 'file', 'system', 'code')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid, "senderId" uuid, "content" text NOT NULL, "type" "public"."chat_messages_type_enum" NOT NULL DEFAULT 'text', "parentId" character varying, "isEdited" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "reactions" jsonb, "attachments" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'professor', 'student')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending_verification', 'pending_approval')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'student', "status" "public"."users_status_enum" NOT NULL DEFAULT 'pending_verification', "avatar" character varying, "phone" character varying, "faculty" character varying, "department" character varying, "studyYear" integer, "bio" text, "refreshToken" character varying, "codeAttempts" integer NOT NULL DEFAULT '0', "emailVerificationToken" character varying, "emailVerificationExpires" TIMESTAMP, "passwordResetToken" character varying, "passwordResetExpires" TIMESTAMP, "termsAcceptedAt" TIMESTAMP, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockoutUntil" TIMESTAMP, "notificationPreferences" jsonb DEFAULT '{}', "favoriteProjects" jsonb DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."team_join_requests_status_enum" AS ENUM('pending', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "team_join_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teamId" uuid NOT NULL, "userId" uuid NOT NULL, "status" "public"."team_join_requests_status_enum" NOT NULL DEFAULT 'pending', "message" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c19829b97d58cf62391932c632a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."milestones_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "milestones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "description" text, "status" "public"."milestones_status_enum" NOT NULL DEFAULT 'pending', "dueDate" date NOT NULL, "completedAt" date, "order" integer NOT NULL DEFAULT '0', "progressPercentage" integer NOT NULL DEFAULT '0', "deliverables" character varying, "projectId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0bdbfe399c777a6a8520ff902d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "projectId" uuid, "authorId" uuid, "parentId" uuid, "isEdited" boolean NOT NULL DEFAULT false, "attachments" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "description" character varying, "entityType" character varying, "entityId" character varying, "projectId" uuid, "userId" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "documentId" uuid, "version" integer NOT NULL, "filename" character varying NOT NULL, "storagePath" character varying NOT NULL, "size" bigint NOT NULL, "changelog" text, "uploadedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_baf26dab035c6d6fc433f9dc6a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('thesis', 'presentation', 'report', 'code', 'media', 'other')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(300) NOT NULL, "description" text, "type" "public"."documents_type_enum" NOT NULL DEFAULT 'other', "filename" character varying NOT NULL, "originalName" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" bigint NOT NULL, "storagePath" character varying NOT NULL, "thumbnailPath" character varying, "extractedText" text, "projectId" uuid, "milestoneId" character varying, "uploadedById" uuid, "currentVersion" integer NOT NULL DEFAULT '1', "isPublic" boolean NOT NULL DEFAULT false, "tags" text, "plagiarismScore" integer, "metadata" jsonb DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluation_criteria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "evaluationId" uuid, "name" character varying NOT NULL, "description" text, "score" numeric(4,2) NOT NULL, "maxScore" numeric(4,2) NOT NULL, "weight" numeric(5,2) NOT NULL DEFAULT '1', "feedback" text, CONSTRAINT "PK_1bf12cd7c46af786eec5987c5c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluation_revisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "evaluationId" uuid NOT NULL, "changedById" uuid, "oldTotalScore" numeric(8,2), "newTotalScore" numeric(8,2), "reason" text NOT NULL, "snapshot" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1c223521ade3aeaf3a87aeb1e63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."evaluations_status_enum" AS ENUM('draft', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."evaluations_phase_enum" AS ENUM('proposal', 'midterm', 'final', 'defense')`);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid, "evaluatorId" uuid, "status" "public"."evaluations_status_enum" NOT NULL DEFAULT 'draft', "phase" "public"."evaluations_phase_enum" NOT NULL, "totalScore" numeric(8,2), "maxScore" numeric(8,2), "generalFeedback" text, "strengths" text, "improvements" text, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ai_analyses_type_enum" AS ENUM('progress_score', 'risk_assessment', 'recommendations', 'completion_prediction', 'quality_assessment')`);
        await queryRunner.query(`CREATE TABLE "ai_analyses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid, "type" "public"."ai_analyses_type_enum" NOT NULL, "score" numeric(5,2), "result" jsonb NOT NULL, "summary" text, "recommendations" text, "model" character varying NOT NULL DEFAULT 'rule-based', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f668f96ca6b8cd3dd8ebbd5c576" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."projects_type_enum" AS ENUM('bachelor_thesis', 'master_thesis', 'research', 'industrial', 'open_source', 'competition')`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('draft', 'proposed', 'approved', 'in_progress', 'review', 'completed', 'archived', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."projects_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "description" text NOT NULL, "objectives" text, "type" "public"."projects_type_enum" NOT NULL DEFAULT 'bachelor_thesis', "status" "public"."projects_status_enum" NOT NULL DEFAULT 'draft', "priority" "public"."projects_priority_enum" NOT NULL DEFAULT 'medium', "coordinatorId" uuid, "createdById" uuid, "teamId" uuid, "startDate" date, "endDate" date, "repository" character varying, "demoUrl" character varying, "tags" text, "technologies" text, "faculty" character varying, "department" character varying, "academicYear" integer, "finalGrade" numeric(4,2), "progressPercentage" integer NOT NULL DEFAULT '0', "isPublic" boolean NOT NULL DEFAULT false, "coverImage" character varying, "rejectionReason" text, "settings" jsonb DEFAULT '{}', "metadata" jsonb DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_395fc399993a21aefc057fbb86" ON "projects" ("coordinatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a27865a7be17886e3088f4a650" ON "projects" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('todo', 'in_progress', 'in_review', 'done', 'blocked')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(300) NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'todo', "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'medium', "projectId" uuid, "milestoneId" uuid, "assigneeId" uuid, "reporterId" uuid, "dueDate" date, "estimatedHours" numeric, "loggedHours" numeric, "order" integer NOT NULL DEFAULT '0', "tags" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teamId" uuid NOT NULL, "invitedEmail" character varying NOT NULL, "invitedUserId" uuid, "invitedById" uuid NOT NULL, "status" "public"."invitations_status_enum" NOT NULL DEFAULT 'pending', "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509" UNIQUE ("token"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_6d1c8c7f705803f0711336a5c33" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_0a72b849753a046462b4c5a8ec2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_9fa0373c1451ad384fc6a74aa8c" FOREIGN KEY ("roomId") REFERENCES "chat_rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_join_requests" ADD CONSTRAINT "FK_45688246cfe338afcaaf21e68fd" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_join_requests" ADD CONSTRAINT "FK_08ffedac86bb67287faa09af28e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "milestones" ADD CONSTRAINT "FK_662a1f9d865fe49768fa369fd0f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_266dea9aee3073a8a5e4d92845f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4548cc4a409b8651ec75f70e280" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_e67cee936823900fc4d5f3feb14" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_5a2cfe6f705df945b20c1b22c71" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_4ea14bf55da75a8c3997e745a28" FOREIGN KEY ("documentId") REFERENCES "documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_versions" ADD CONSTRAINT "FK_3dfffbb1a9580587901d2469e7f" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_fe6ebd6e679c0feee3a7ecc0354" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_5aad3bc717a4f483887ec61dbc8" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation_criteria" ADD CONSTRAINT "FK_25579521d4f1a714545acf761d7" FOREIGN KEY ("evaluationId") REFERENCES "evaluations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation_revisions" ADD CONSTRAINT "FK_8ac177e442cb083e8297151ccd2" FOREIGN KEY ("evaluationId") REFERENCES "evaluations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation_revisions" ADD CONSTRAINT "FK_2f46f7cd2570f28c33220b96590" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_3b60ad2dfd0fbcf0501d46cf85f" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_d9bc0902066eeac8d46a333efad" FOREIGN KEY ("evaluatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_analyses" ADD CONSTRAINT "FK_569c9204d574bc15f99ac0d870b" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_f55144dc92df43cd1dad5d29b90" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_395fc399993a21aefc057fbb868" FOREIGN KEY ("coordinatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_2f789e58a882d8dd5b936c747c2" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_6dc5020fc4c6814347816455e7a" FOREIGN KEY ("milestoneId") REFERENCES "milestones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_113cb1411bac0e764b922699d4b" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_3eac42453dddb5edbfb8bf66a53" FOREIGN KEY ("invitedUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_b60325e5302be0dad38b423314c" FOREIGN KEY ("invitedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_b60325e5302be0dad38b423314c"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_3eac42453dddb5edbfb8bf66a53"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_113cb1411bac0e764b922699d4b"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_7ecc6be7d74a3f441f7aa5215ef"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_6dc5020fc4c6814347816455e7a"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e08fca67ca8966e6b9914bf2956"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_2f789e58a882d8dd5b936c747c2"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_395fc399993a21aefc057fbb868"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_f55144dc92df43cd1dad5d29b90"`);
        await queryRunner.query(`ALTER TABLE "ai_analyses" DROP CONSTRAINT "FK_569c9204d574bc15f99ac0d870b"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_d9bc0902066eeac8d46a333efad"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_3b60ad2dfd0fbcf0501d46cf85f"`);
        await queryRunner.query(`ALTER TABLE "evaluation_revisions" DROP CONSTRAINT "FK_2f46f7cd2570f28c33220b96590"`);
        await queryRunner.query(`ALTER TABLE "evaluation_revisions" DROP CONSTRAINT "FK_8ac177e442cb083e8297151ccd2"`);
        await queryRunner.query(`ALTER TABLE "evaluation_criteria" DROP CONSTRAINT "FK_25579521d4f1a714545acf761d7"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_5aad3bc717a4f483887ec61dbc8"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_fe6ebd6e679c0feee3a7ecc0354"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_3dfffbb1a9580587901d2469e7f"`);
        await queryRunner.query(`ALTER TABLE "document_versions" DROP CONSTRAINT "FK_4ea14bf55da75a8c3997e745a28"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_5a2cfe6f705df945b20c1b22c71"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_e67cee936823900fc4d5f3feb14"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4548cc4a409b8651ec75f70e280"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_266dea9aee3073a8a5e4d92845f"`);
        await queryRunner.query(`ALTER TABLE "milestones" DROP CONSTRAINT "FK_662a1f9d865fe49768fa369fd0f"`);
        await queryRunner.query(`ALTER TABLE "team_join_requests" DROP CONSTRAINT "FK_08ffedac86bb67287faa09af28e"`);
        await queryRunner.query(`ALTER TABLE "team_join_requests" DROP CONSTRAINT "FK_45688246cfe338afcaaf21e68fd"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_9fa0373c1451ad384fc6a74aa8c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_0a72b849753a046462b4c5a8ec2"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_6d1c8c7f705803f0711336a5c33"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_status_enum"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a27865a7be17886e3088f4a650"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_395fc399993a21aefc057fbb86"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."projects_type_enum"`);
        await queryRunner.query(`DROP TABLE "ai_analyses"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analyses_type_enum"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP TYPE "public"."evaluations_phase_enum"`);
        await queryRunner.query(`DROP TYPE "public"."evaluations_status_enum"`);
        await queryRunner.query(`DROP TABLE "evaluation_revisions"`);
        await queryRunner.query(`DROP TABLE "evaluation_criteria"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`DROP TABLE "document_versions"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "milestones"`);
        await queryRunner.query(`DROP TYPE "public"."milestones_status_enum"`);
        await queryRunner.query(`DROP TABLE "team_join_requests"`);
        await queryRunner.query(`DROP TYPE "public"."team_join_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_type_enum"`);
        await queryRunner.query(`DROP TABLE "chat_rooms"`);
        await queryRunner.query(`DROP TYPE "public"."chat_rooms_type_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "team_members"`);
        await queryRunner.query(`DROP TYPE "public"."team_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "teams"`);
    }

}
